#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git checkout master
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g ts-node
  - npm install -g typescript

script:
  - npm run-script build
  - npm version patch -m "[CHORE] Bump Version %s [skip ci]"

before_deploy:
  - git push https://$GITHUB_TOKEN@github.com/wordythebyrd/agile-retrospective master
  - git push https://$GITHUB_TOKEN@github.com/wordythebyrd/agile-retrospective --tags

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change